spring:
  application:
    name: sse-update

  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    template:
      default-destination: demo-queue


  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update